import { z } from "zod";

const optionnel = () => z.string().trim().default("");

/// Validation d'un site — 66 champs, tous du texte libre (voir
/// docs/MIGRATION.md). Seuls nom/site/n_affaire sont obligatoires :
/// n_affaire sert de clé de rapprochement à l'import (voir
/// scripts/mappers/sites.ts) et détermine "hors contrat".
export const siteSchema = z.object({
  nom: z.string().trim().min(1, "Le nom du client est obligatoire"),
  site: z.string().trim().min(1, "Le nom du site est obligatoire"),
  n_affaire: z.string().trim().min(1, "Le N° Affaire est obligatoire"),
  commune: optionnel(),
  code_postal: optionnel(),
  adresse: optionnel(),
  complement_adresse: optionnel(),
  epi_specifique: optionnel(),
  habilitation_specifique: optionnel(),
  moyen_acces: optionnel(),
  jour_acces: optionnel(),
  heures_acces: optionnel(),
  delai_intervention: optionnel(),
  interlocuteur_site: optionnel(),
  tel_fixe_interlocuteur_site: optionnel(),
  portable_interlocuteur_site: optionnel(),
  courriel_interlocuteur_site: optionnel(),
  freq_entretien_an: optionnel(),
  interlocuteur_tiers: optionnel(),
  tel_fixe_tiers: optionnel(),
  portable_tiers: optionnel(),
  courriel_tiers: optionnel(),
  remarques_libres: optionnel(),
  nb_heures_vendues: optionnel(),
  nb_heures_vendues_assistant: optionnel(),
  qte_heures_programmees: optionnel(),
  qte_heures_restantes: optionnel(),
  taux_horaire_regie: optionnel(),
  taux_horaire_vendu: optionnel(),
  forfait_deplacement: optionnel(),
  date_offre: optionnel(),
  date_prise_effet_contrat: optionnel(),
  date_fin_contrat: optionnel(),
  duree_contrat: optionnel(),
  montant_contrat_av: optionnel(),
  reference_offre_ogs: optionnel(),
  responsable_contrat: optionnel(),
  tel_fixe_responsable: optionnel(),
  portable_responsable: optionnel(),
  courriel_responsable: optionnel(),
  adresse_facturation: optionnel(),
  code_postal_facturation: optionnel(),
  commune_facturation: optionnel(),
  complement_adresse_facturation: optionnel(),
  interlocuteur_facturation: optionnel(),
  tel_fixe_interlocuteur_facturation: optionnel(),
  portable_interlocuteur_facturation: optionnel(),
  courriel_interlocuteur_facturation: optionnel(),
  freq_factu_annuelle: optionnel(),
  date_revision: optionnel(),
  formule_revision_entretien: optionnel(),
  formule_revision_depannage: optionnel(),
  date_indice_s: optionnel(),
  valeur_indice_s: optionnel(),
  date_indice_ch: optionnel(),
  valeur_indice_ch: optionnel(),
  date_indice_s_prime: optionnel(),
  valeur_indice_s_prime: optionnel(),
  date_indice_ch_prime: optionnel(),
  valeur_indice_ch_prime: optionnel(),
  montant_contrat_av_revise: optionnel(),
  taux_horaire_revise: optionnel(),
  forfait_deplacement_revise: optionnel(),
  modif_ri_ou_bg: optionnel(),
});

export type SiteInput = z.infer<typeof siteSchema>;

/// Regroupement des champs pour le formulaire — mêmes groupes, même
/// ordre et mêmes libellés que client_field_group.dart (Flutter),
/// pour un portage fidèle.
export const groupesChampsSite: {
  titre: string;
  adminOnly: boolean;
  champs: { cle: keyof SiteInput; label: string }[];
}[] = [
  {
    titre: "Identité & Site",
    adminOnly: false,
    champs: [
      { cle: "nom", label: "Client" },
      { cle: "site", label: "Site" },
      { cle: "n_affaire", label: "N°Affaire" },
      { cle: "code_postal", label: "Code Postal" },
      { cle: "commune", label: "Commune" },
      { cle: "adresse", label: "Adresse" },
      { cle: "complement_adresse", label: "Complément d'adresse" },
    ],
  },
  {
    titre: "Accès & Sécurité",
    adminOnly: false,
    champs: [
      { cle: "epi_specifique", label: "EPI spécifique" },
      { cle: "habilitation_specifique", label: "Habilitation spécifique" },
      { cle: "moyen_acces", label: "Moyen d'accès" },
      { cle: "jour_acces", label: "Jour d'accès" },
      { cle: "heures_acces", label: "Heures d'accès" },
      { cle: "delai_intervention", label: "Délai d'intervention" },
    ],
  },
  {
    titre: "Contacts & Suivi",
    adminOnly: false,
    champs: [
      { cle: "interlocuteur_site", label: "Interlocuteur site" },
      { cle: "tel_fixe_interlocuteur_site", label: "Tel Fixe interlocuteur site" },
      { cle: "portable_interlocuteur_site", label: "Portable interlocuteur site" },
      { cle: "courriel_interlocuteur_site", label: "Courriel interlocuteur site" },
      { cle: "freq_entretien_an", label: "Fréq. entretien / an" },
      { cle: "interlocuteur_tiers", label: "Interlocuteur Tiers" },
      { cle: "tel_fixe_tiers", label: "Tel Fixe Tiers" },
      { cle: "portable_tiers", label: "Portable Tiers" },
      { cle: "courriel_tiers", label: "Courriel Tiers" },
      { cle: "remarques_libres", label: "Remarques libres" },
    ],
  },
  {
    titre: "Heures & Tarifs",
    adminOnly: true,
    champs: [
      { cle: "nb_heures_vendues", label: "Nb Heures vendues" },
      { cle: "nb_heures_vendues_assistant", label: "Nb Heures vendues assistant" },
      { cle: "qte_heures_programmees", label: "Qté heures programmées" },
      { cle: "qte_heures_restantes", label: "Qté heures restantes" },
      { cle: "taux_horaire_regie", label: "Taux horaire régie" },
      { cle: "taux_horaire_vendu", label: "Taux horaire vendu" },
      { cle: "forfait_deplacement", label: "Forfait déplacement" },
    ],
  },
  {
    titre: "Contrat",
    adminOnly: true,
    champs: [
      { cle: "date_offre", label: "Date de l'offre" },
      { cle: "date_prise_effet_contrat", label: "Date de prise d'effet" },
      { cle: "date_fin_contrat", label: "Date de fin de contrat" },
      { cle: "duree_contrat", label: "Durée" },
      { cle: "montant_contrat_av", label: "Montant Contrat + AV" },
      { cle: "reference_offre_ogs", label: "Référence offre OGS" },
      { cle: "responsable_contrat", label: "Responsable contrat" },
      { cle: "tel_fixe_responsable", label: "Tel Fixe responsable" },
      { cle: "portable_responsable", label: "Portable responsable" },
      { cle: "courriel_responsable", label: "Courriel responsable" },
    ],
  },
  {
    titre: "Facturation",
    adminOnly: true,
    champs: [
      { cle: "adresse_facturation", label: "Adresse facturation" },
      { cle: "code_postal_facturation", label: "Code Postal facturation" },
      { cle: "commune_facturation", label: "Commune facturation" },
      { cle: "complement_adresse_facturation", label: "Complément d'adresse facturation" },
      { cle: "interlocuteur_facturation", label: "Interlocuteur facturation" },
      { cle: "tel_fixe_interlocuteur_facturation", label: "Tel Fixe interlocuteur facturation" },
      { cle: "portable_interlocuteur_facturation", label: "Portable interlocuteur facturation" },
      { cle: "courriel_interlocuteur_facturation", label: "Courriel interlocuteur facturation" },
      { cle: "freq_factu_annuelle", label: "Fréq. facturation annuelle" },
    ],
  },
  {
    titre: "Révision & Indices",
    adminOnly: true,
    champs: [
      { cle: "date_revision", label: "Date de révision" },
      { cle: "formule_revision_entretien", label: "Formule révision entretien" },
      { cle: "formule_revision_depannage", label: "Formule révision dépannage" },
      { cle: "date_indice_s", label: "Date Indice S" },
      { cle: "valeur_indice_s", label: "Valeur indice S" },
      { cle: "date_indice_ch", label: "Date Indice CH" },
      { cle: "valeur_indice_ch", label: "Valeur indice CH" },
      { cle: "date_indice_s_prime", label: "Date Indice S°" },
      { cle: "valeur_indice_s_prime", label: "Valeur indice S°" },
      { cle: "date_indice_ch_prime", label: "Date Indice CH°" },
      { cle: "valeur_indice_ch_prime", label: "Valeur indice CH°" },
      { cle: "montant_contrat_av_revise", label: "Montant Contrat+AV révisé" },
      { cle: "taux_horaire_revise", label: "Taux horaire révisé" },
      { cle: "forfait_deplacement_revise", label: "Forfait déplacement révisé" },
      { cle: "modif_ri_ou_bg", label: "Modif RI ou BG" },
    ],
  },
];
