import { str, type Mapper } from "./types";

/// `clients` Firestore (1 doc = 1 site) → `sites` Supabase. Tous les
/// champs sont du texte des deux côtés (voir docs/MIGRATION.md) — pas
/// de conversion de type ici, juste camelCase → snake_case.
export const sitesMapper: Mapper = {
  name: "sites",
  table: "sites",
  collection: "clients",
  toRow: (doc) => {
    const d = doc.data;
    return {
      legacy_id: doc.id,
      nom: str(d, "nom"),
      site: str(d, "site"),
      n_affaire: str(d, "nAffaire"),
      commune: str(d, "commune"),
      code_postal: str(d, "codePostal"),
      adresse: str(d, "adresse"),
      complement_adresse: str(d, "complementAdresse"),
      epi_specifique: str(d, "epiSpecifique"),
      habilitation_specifique: str(d, "habilitationSpecifique"),
      moyen_acces: str(d, "moyenAcces"),
      jour_acces: str(d, "jourAcces"),
      heures_acces: str(d, "heuresAcces"),
      delai_intervention: str(d, "delaiIntervention"),
      interlocuteur_site: str(d, "interlocuteurSite"),
      tel_fixe_interlocuteur_site: str(d, "telFixeInterlocuteurSite"),
      portable_interlocuteur_site: str(d, "portableInterlocuteurSite"),
      courriel_interlocuteur_site: str(d, "courrielInterlocuteurSite"),
      freq_entretien_an: str(d, "freqEntretienAn"),
      interlocuteur_tiers: str(d, "interlocuteurTiers"),
      tel_fixe_tiers: str(d, "telFixeTiers"),
      portable_tiers: str(d, "portableTiers"),
      courriel_tiers: str(d, "courrielTiers"),
      remarques_libres: str(d, "remarquesLibres"),
      nb_heures_vendues: str(d, "nbHeuresVendues"),
      nb_heures_vendues_assistant: str(d, "nbHeuresVenduesAssistant"),
      qte_heures_programmees: str(d, "qteHeuresProgrammees"),
      qte_heures_restantes: str(d, "qteHeuresRestantes"),
      taux_horaire_regie: str(d, "tauxHoraireRegie"),
      taux_horaire_vendu: str(d, "tauxHoraireVendu"),
      forfait_deplacement: str(d, "forfaitDeplacement"),
      date_offre: str(d, "dateOffre"),
      date_prise_effet_contrat: str(d, "datePriseEffetContrat"),
      date_fin_contrat: str(d, "dateFinContrat"),
      duree_contrat: str(d, "dureeContrat"),
      montant_contrat_av: str(d, "montantContratAv"),
      reference_offre_ogs: str(d, "referenceOffreOgs"),
      responsable_contrat: str(d, "responsableContrat"),
      tel_fixe_responsable: str(d, "telFixeResponsable"),
      portable_responsable: str(d, "portableResponsable"),
      courriel_responsable: str(d, "courrielResponsable"),
      adresse_facturation: str(d, "adresseFacturation"),
      code_postal_facturation: str(d, "codePostalFacturation"),
      commune_facturation: str(d, "communeFacturation"),
      complement_adresse_facturation: str(d, "complementAdresseFacturation"),
      interlocuteur_facturation: str(d, "interlocuteurFacturation"),
      tel_fixe_interlocuteur_facturation: str(d, "telFixeInterlocuteurFacturation"),
      portable_interlocuteur_facturation: str(d, "portableInterlocuteurFacturation"),
      courriel_interlocuteur_facturation: str(d, "courrielInterlocuteurFacturation"),
      freq_factu_annuelle: str(d, "freqFactuAnnuelle"),
      date_revision: str(d, "dateRevision"),
      formule_revision_entretien: str(d, "formuleRevisionEntretien"),
      formule_revision_depannage: str(d, "formuleRevisionDepannage"),
      date_indice_s: str(d, "dateIndiceS"),
      valeur_indice_s: str(d, "valeurIndiceS"),
      date_indice_ch: str(d, "dateIndiceCh"),
      valeur_indice_ch: str(d, "valeurIndiceCh"),
      date_indice_s_prime: str(d, "dateIndiceSPrime"),
      valeur_indice_s_prime: str(d, "valeurIndiceSPrime"),
      date_indice_ch_prime: str(d, "dateIndiceChPrime"),
      valeur_indice_ch_prime: str(d, "valeurIndiceChPrime"),
      montant_contrat_av_revise: str(d, "montantContratAvRevise"),
      taux_horaire_revise: str(d, "tauxHoraireRevise"),
      forfait_deplacement_revise: str(d, "forfaitDeplacementRevise"),
      modif_ri_ou_bg: str(d, "modifRiOuBg"),
    };
  },
};
